# Generated by Django 5.1 on 2024-08-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
